### ISSUE TITLE
[Inquiry] Request to use ‘evaluate_fid.py’

### ISSUE THREAD

**Issue by YeongHyeon** [KHU-AGI/GUIDE#1]
Hi,
Thank you for sharing this great work.
I am interested in this work and trying to forget my other identity through this source code.

The unlearning process has worked successfully for me.
However, evaluating an unlearned model via 'evaluate_fid.py' seems to require another preparation as attached part of the code.

Can I ask for your help about that?

-----
https://github.com/KHU-AGI/GUIDE/blob/9cd9c9d9b4a1ef2958c7e48c8d5b0d7905e51007/evaluate_fid.py#L439-L440

**Comment by TY-LEE-KR** [comment]
Have you tried running the [evaluate_fid.py](https://github.com/KHU-AGI/GUIDE/blob/main/evaluate_fid.py)?

There is no additional preparation needed to run this code.
If the parts you mentioned are not ready, our code will automatically generate the necessary components.

And what does an untrained model mean?
Does it refer to the original model?
Please let me know. I might be able to provide additional help.

I hope that my response may address your question.

**Comment by YeongHyeon** [comment]
Thank you for your fast response!
I solved this by adding 'skip_pretrained = True' to line 441.

By the way, I would like to experiment as shown in the paper completely. 
Can I ask how many $w_u$ should I extract from each of the (1) randomly sampled noise vectors, (2) FFHQ, and (3) CelebAHQ?

Thank you once again!

**Comment by TY-LEE-KR** [comment]
We used 10~20(almost 20) identities in each scenario.

**Comment by YeongHyeon** [comment]
Thank you for your response.
If you don't mind, can I ask IDs of images that you used for experiments?
If it is available, it will be very helpful for research community.

**Comment by YeongHyeon** [comment]
Hi again,
If you don't mind, please consider this again.
Thank you!

**Comment by TY-LEE-KR** [comment]
We apologize for the delayed response.

We attempted to find the exact identity data but were only able to retrieve part of it. For example, in the case of CelebA-HQ, we used identities such as $ID = [512, 513, 1228, 3000, ...]$. (You can find the $ID$ in the official CelebA annotations.)

Our selection was based on image diversity. Many identities in the datasets have very similar images (e.g., differing only by watermarks), which didn’t align with our multi-image scenario. Therefore, we chose identities with a range of clean and distinct images.

We hope this response is helpful for your research. If you need additional support, please feel free to email us.
