### ISSUE TITLE
How did you calculate the average of latent space

### ISSUE THREAD

**Issue by mmitchef** [KHU-AGI/GUIDE#3]
Hi,

This is a great job and thanks for sharing your code. Could you please describe how did you calculate the average latent space of EG3D.

Thanks

**Comment by JJuOn** [comment]
Hi, we sampled 4,096 random noises and produced their corresponding latent codes using EG3D's mapping network.  
Finally, the average latent code can be obtained by averaging them.

**Comment by mmitchef** [comment]
@JJuOn Thanks for your response and providing the information.
